### ISSUE TITLE
Minor Error in Restart Script?

### ISSUE THREAD

**Issue by trevorhodges** [epidataio/epidata-install#4]
While performing a review of the epidata-install scripts it appears that the 'restart' function in the epidata script executes a 'start' then 'stop'. Seems as though it should 'stop' and then 'start'?

https://github.com/epidataio/epidata-install/blob/a5500c2bf6cb0d484b81a23712488c9232fdba94/bin/epidata#L73

**Comment by knguyen2206** [comment]
That's correct. It should be stop and start. @trevorhodges can you please file a Pull Request?

**Comment by trevorhodges** [comment]
@knguyen2206 @srinibadri Not 100% sure, but I don't believe I have permissions

**Comment by knguyen2206** [comment]
@trevorhodges you can simply fork the repo and create a Pull Request from it. We'll review and merge it.

**Comment by srinibadri** [comment]
@trevorhodges thanks for finding the issue and resolving it!
